jobs:
- deployment: biceptoAzure
  displayName: 'Deploy bicep to Azure'
  environment: $(DEPLOY_ENVIRONMENT)
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - task: AzureCLI@2
          displayName: 'deploy bicep template'
          inputs:
            azureSubscription: $(AZURE_SUBSCRIPTION) 
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az deployment sub create  \
              --template-file $(Build.SourcesDirectory)/main.bicep \
              -l westeurope \
              --no-prompt \
              --parameters contributor_object_id=$(CONTRIBUTOR_OBJECT_ID) \
                            azure_client_id=$(AZURE_CLIENT_ID) \
                            azure_client_secret=$(AZURE_CLIENT_SECRET) \
                            azure_tenant_id=$(AZURE_TENANT_ID) \
                            resource_group=$(RESOURCE_GROUP) \
                            deploy_environment=$(DEPLOY_ENVIRONMENT) \
              --parameters @main.parameters.json