name: Deploy bicep files to test on master commit

trigger:
- master

pool:
  name: local_pool
  demands:
    - agent.os -equals Darwin

# Add the actual application code repository so this can be used during deployment  
resources:
  repositories:
  - repository: microapp
    type: github
    endpoint: TimMolleman
    name: TimMolleman/microapp
    ref: master
    trigger:
    - master


stages:
# First checkout microapp_bicep and the microapp repository, also list available source files from these checkouts
- stage: Checkouts
  jobs:
    - job:
      displayName: Checkout repositories
      steps:
        - checkout: self
        - checkout: microapp
        - script: ls $(Build.SourcesDirectory)


# Run linting on the bicep file, warnings are shown but this doesn't stop the pipeline. Errors do
- stage: Lint
  jobs:
    - template: pipeline-templates/lint.yml

# Run validation on the deployment subscription
- stage: Validate
  jobs:
    - template: pipeline-templates/validate.yml

# Lastly deploy the bicep file code to Azure
- stage: Deploy
  jobs:
    - template: pipeline-templates/deploy.yml
  